export enum Specialty {
  CARDIOLOGY = 'CARDIOLOGY',
  DERMATOLOGY = 'DERMATOLOGY',
  GINECOLOGY = 'GINECOLOGY',
  OBSTETRICS = 'OBSTETRICS',
  PEDIATRICS = 'PEDIATRICS',
  PSYCHIATRY = 'PSYCHIATRY',
  ORTHOPEDICS = 'ORTHOPEDICS',
  TRAUMATOLOGY = 'TRAUMATOLOGY',
  OPHTHALMOLOGY = 'OPHTHALMOLOGY',
  NEUROLOGY = 'NEUROLOGY',
  ONCOLOGY = 'ONCOLOGY',
  PEDIATRIC_CARDIOLOGY = 'PEDIATRIC_CARDIOLOGY',
  ENDOCRINOLOGY = 'ENDOCRINOLOGY',
  GASTROENTEROLOGY = 'GASTROENTEROLOGY',
  HEMATOLOGY = 'HEMATOLOGY',
  INFECTIOUS_DISEASES = 'INFECTIOUS_DISEASES',
  NEPHROLOGY = 'NEPHROLOGY',
  PNEUMOLOGY = 'PNEUMOLOGY',
  UROLOGY = 'UROLOGY',
  RADIOLOGY = 'RADIOLOGY',
  ANESTHESIOLOGY = 'ANESTHESIOLOGY',
  GENERAL_SURGERY = 'GENERAL_SURGERY',
  PLASTIC_SURGERY = 'PLASTIC_SURGERY',
  INTERNAL_MEDICINE = 'INTERNAL_MEDICINE',
  GERIATRICS = 'GERIATRICS'
}

export type BedType = 'INFIRMARY' | 'UTI';

export interface DailyModel {
  id: number;
  type: BedType;
  specialty: Specialty;
  value: number;
}

export interface DailyRequestModel {
  type: BedType;
  specialty: Specialty;
  value: number;
}